controllers:
    resource: ../src/Controller/
    type: attribute

rechercher_acteur_ajax:
    path: /rechercher-acteur-ajax
    controller: App\Controller\ActeurController::rechercherActeurAjax
    methods: [GET]